### ISSUE TITLE
Having trouble installing the package in conda environment with python 3.7.4 (AssertionError due to word in capital letters)))

### ISSUE THREAD

**Issue by acruzpr** [ifduyue/python-xxhash#28]
In a fresh python 3.7.4 conda environment:

```
conda create -n new python=3.7.4
Collecting package metadata (current_repodata.json): done
Solving environment: done


==> WARNING: A newer version of conda exists. <==
  current version: 4.7.5
  latest version: 4.7.11

Please update conda by running

    $ conda update -n base -c defaults conda



## Package Plan ##

  environment location: /home/acruz/miniconda3/envs/new

  added / updated specs:
    - python=3.7.4


The following NEW packages will be INSTALLED:

  _libgcc_mutex      pkgs/main/linux-64::_libgcc_mutex-0.1-main
  ca-certificates    pkgs/main/linux-64::ca-certificates-2019.5.15-1
  certifi            pkgs/main/linux-64::certifi-2019.6.16-py37_1
  libedit            pkgs/main/linux-64::libedit-3.1.20181209-hc058e9b_0
  libffi             pkgs/main/linux-64::libffi-3.2.1-hd88cf55_4
  libgcc-ng          pkgs/main/linux-64::libgcc-ng-9.1.0-hdf63c60_0
  libstdcxx-ng       pkgs/main/linux-64::libstdcxx-ng-9.1.0-hdf63c60_0
  ncurses            pkgs/main/linux-64::ncurses-6.1-he6710b0_1
  openssl            pkgs/main/linux-64::openssl-1.1.1c-h7b6447c_1
  pip                pkgs/main/linux-64::pip-19.1.1-py37_0
  python             pkgs/main/linux-64::python-3.7.4-h265db76_0
  readline           pkgs/main/linux-64::readline-7.0-h7b6447c_5
  setuptools         pkgs/main/linux-64::setuptools-41.0.1-py37_0
  sqlite             pkgs/main/linux-64::sqlite-3.29.0-h7b6447c_0
  tk                 pkgs/main/linux-64::tk-8.6.8-hbc83047_0
  wheel              pkgs/main/linux-64::wheel-0.33.4-py37_0
  xz                 pkgs/main/linux-64::xz-5.2.4-h14c3975_4
  zlib               pkgs/main/linux-64::zlib-1.2.11-h7b6447c_3


Proceed ([y]/n)? y

Preparing transaction: done
Verifying transaction: done
Executing transaction: done
#
# To activate this environment, use
#
#     $ conda activate new
#
# To deactivate an active environment, use
#
#     $ conda deactivate
```

 Then try to install xxhash

```
conda activate new
pip install xxhash

7.4.0
Collecting xxhash
  Using cached https://files.pythonhosted.org/packages/4a/f9/f83b3ab3bd1bf50ae7b6c21f9fa28107df38c9283c721ce40688ea443eb9/xxhash-1.3.0.tar.gz
Building wheels for collected packages: xxhash
  Building wheel for xxhash (setup.py) ... error
  ERROR: Complete output from command /home/acruz/miniconda3/envs/new/bin/python -u -c 'import setuptools, tokenize;__file__='"'"'/tmp/pip-install-g77w7dxw/xxhash/setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d /tmp/pip-wheel-yy4xo0ku --python-tag cp37:
  ERROR: 7.4.0
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build/lib.linux-x86_64-3.7
  creating build/lib.linux-x86_64-3.7/xxhash
  copying xxhash/__init__.py -> build/lib.linux-x86_64-3.7/xxhash
  running build_ext
  building 'cpython' extension
  creating build/temp.linux-x86_64-3.7
  creating build/temp.linux-x86_64-3.7/xxhash
  creating build/temp.linux-x86_64-3.7/deps
  creating build/temp.linux-x86_64-3.7/deps/xxhash
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ideps/xxhash -I/home/acruz/miniconda3/envs/new/include/python3.7m -c xxhash/cpython.c -o build/temp.linux-x86_64-3.7/xxhash/cpython.o
  gcc -pthread -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -Ideps/xxhash -I/home/acruz/miniconda3/envs/new/include/python3.7m -c deps/xxhash/xxhash.c -o build/temp.linux-x86_64-3.7/deps/xxhash/xxhash.o
  gcc -pthread -shared -L/home/acruz/miniconda3/envs/new/lib -Wl,-rpath=/home/acruz/miniconda3/envs/new/lib -Wl,--no-as-needed -Wl,--sysroot=/ build/temp.linux-x86_64-3.7/xxhash/cpython.o build/temp.linux-x86_64-3.7/deps/xxhash/xxhash.o -o build/lib.linux-x86_64-3.7/xxhash/cpython.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so
  installing to build/bdist.linux-x86_64/wheel
  running install
  running install_lib
  creating build/bdist.linux-x86_64
  creating build/bdist.linux-x86_64/wheel
  creating build/bdist.linux-x86_64/wheel/xxhash
  copying build/lib.linux-x86_64-3.7/xxhash/cpython.cpython-@PYVERNODOTS@m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/wheel/xxhash
  copying build/lib.linux-x86_64-3.7/xxhash/__init__.py -> build/bdist.linux-x86_64/wheel/xxhash
  running install_egg_info
  running egg_info
  writing xxhash.egg-info/PKG-INFO
  writing dependency_links to xxhash.egg-info/dependency_links.txt
  writing top-level names to xxhash.egg-info/top_level.txt
  reading manifest file 'xxhash.egg-info/SOURCES.txt'
  reading manifest template 'MANIFEST.in'
  warning: no previously-included files matching '__pycache__' found anywhere in distribution
  warning: no previously-included files matching '*.py[co]' found anywhere in distribution
  writing manifest file 'xxhash.egg-info/SOURCES.txt'
  Copying xxhash.egg-info to build/bdist.linux-x86_64/wheel/xxhash-1.3.0-py3.7.egg-info
  running install_scripts
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "/tmp/pip-install-g77w7dxw/xxhash/setup.py", line 51, in <module>
      ext_modules=ext_modules,
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/site-packages/setuptools/__init__.py", line 145, in setup
      return distutils.core.setup(**attrs)
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/distutils/core.py", line 148, in setup
      dist.run_commands()
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/distutils/dist.py", line 966, in run_commands
      self.run_command(cmd)
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/distutils/dist.py", line 985, in run_command
      cmd_obj.run()
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 230, in run
      impl_tag, abi_tag, plat_tag = self.get_tag()
    File "/home/acruz/miniconda3/envs/new/lib/python3.7/site-packages/wheel/bdist_wheel.py", line 179, in get_tag
      assert tag == supported_tags[0], "%s != %s" % (tag, supported_tags[0])
    AssertionError: ('cp37', 'cp@pyvernodots@m', 'linux_x86_64') != ('cp37', 'cp@PYVERNODOTS@m', 'linux_x86_64')
  ----------------------------------------
  ERROR: Failed building wheel for xxhash
  Running setup.py clean for xxhash
Failed to build xxhash
Installing collected packages: xxhash
  Running setup.py install for xxhash ... done
Successfully installed xxhash-1.3.0

```

**Comment by ifduyue** [comment]
It's a bug of conda python 3.7.4 https://github.com/conda/conda/issues/9084#issuecomment-520410712

**Comment by ifduyue** [comment]
Now it's fixed https://github.com/ContinuumIO/anaconda-issues/issues/11195#issuecomment-521052981
