### ISSUE TITLE
setup.py fails trying to read README.rst

### ISSUE THREAD

**Issue by blakev** [ifduyue/python-xxhash#31]
```
| DEBUG: Executing shell function do_compile
| Traceback (most recent call last):
|   File "setup.py", line 35, in <module>
|     long_description=open('README.rst', 'r').read(),
|   File "/home/workdir/build/tmp/sysroots/x86_64-linux/usr/lib/python3.5/encodings/ascii.py", line 26, in decode
|     return codecs.ascii_decode(input, self.errors)[0]
| UnicodeDecodeError: 'ascii' codec can't decode byte 0xc2 in position 6178: ordinal not in range(128)
| ERROR: python3 setup.py build_ext execution failed.
| WARNING: /home/workdir/build/tmp/work/cortexa9hf-vfp-neon-poky-linux-gnueabi/python3-xxhash/1.4.1-r1/temp/run.do_compile.1237:1 exit 1 from
|   exit 1
```
It's niche, but the setup fails in a build system where the default encoding is `ascii`. Specifically the `±` character isn't there. The fix is to explicitly set the `encoding=` value to `utf-8`; which is the sane default on all modern systems.

**setup.py**
```python
    long_description=open('README.rst', 'r').read(),
# -->
    long_description=open('README.rst', 'r', encoding='utf-8').read(),
```

**Comment by ifduyue** [comment]
v1.4.2 released https://pypi.org/project/xxhash/1.4.2/
