### ISSUE TITLE
Blender 3.4.1: ModuleNotFoundError: No module named 'xxhash._xxhash'

### ISSUE THREAD

**Issue by schoenid** [ifduyue/python-xxhash#62]
While using xxhash 3.2.0 from https://pypi.org/project/xxhash/ in Blender 3.4.1 errors are thrown, trying to enable some modules.

Example:
```
Traceback (most recent call last):
  File "...\AppData\Roaming\Blender Foundation\Blender\3.4\scripts\addons\cad_mesh_dimensions.py", line 47, in <module>
    import xxhash
  File "E:\Programme\Blender\3.4\python\lib\xxhash\__init__.py", line 1, in <module>
    from ._xxhash import (
ModuleNotFoundError: No module named 'xxhash._xxhash'
```

The modules can't be used.

As I found by searches, xxhash 3.0.0 mus be used, but can't be found on https://pypi.org

**Comment by schoenid** [comment]
Sorry ...
My browser did first not show all packages ... found now xxhash-3.2.0-cp310-cp310-win_amd64.whl which works perfectly!
