### ISSUE TITLE
Installation issue with Intel (undefined symbol: _intel_fast_memcpy)

### ISSUE THREAD

**Issue by a-deblois** [ifduyue/python-xxhash#80]
Hello everyone,

I am trying to install gemseo, which has xxhash as a dependency. I am getting a problem at the runtime, and I am been researching quite heavily to resolve this without success. See below for the error message. Would appreciate any help.

Python 3.8.18 was installed with gcc 8.1. What is very confusing is that ldd on the _xxhash.cpython-38-x86_64-linux-gnu.so does not point to any intel library. FYI: We do have the intel libraries installed, and my LD_LIBRARY_PATH has the path to them.

I also tried via the tar ball with the same outcome.

Some google search suggest to link with the intel compiler, but I have not been able to see what flag specifies the linker itself.
Any idea for this behavior?
Also, I did not see any call to _intel_fast_memcpy in the xxhash source code...

thanks for your help!

>>> import xxhash
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/test/Python-3.8.18/lib/python3.8/site-packages/xxhash/__init__.py", line 1, in <module>
    from ._xxhash import (
ImportError: /test/Python-3.8.18/lib/python3.8/site-packages/xxhash/_xxhash.cpython-38-x86_64-linux-gnu.so: undefined symbol: _intel_fast_memcpy

**Comment by ifduyue** [comment]
Hi @a-deblois, I can't reproduce, could you provide more infomation like OS version?

<img width="554" alt="image" src="https://github.com/user-attachments/assets/b0a31084-b003-4b84-9910-75657f1d3e8b">

**Comment by ifduyue** [comment]
Guess you're using intel compiler?
