### ISSUE TITLE
Fails to install via dependency on linux

### ISSUE THREAD

**Issue by tsx** [ifduyue/python-xxhash#9]
Hi,

I'm having an issue installing latest 0.5.0 release on Debian Linux 8.3.

Installation fails, mentioning the following macosx package (that was added on downloads page and was not present in previous version)
xxhash-0.5.0.macosx-10.10-x86_64.tar.gz (md5) 
built for Darwin-14.5.0	"dumb" binary

pip -V => pip 1.5.6, upgrading doesn't help as well.

# Reproduction steps:
```
#!/bin/bash
virtualenv venv
mkdir -p dep
echo "from setuptools import setup" > dep/setup.py
echo "setup(name='dep', setup_requires=['xxhash'])" >> dep/setup.py
echo './dep' > requirements.txt
venv/bin/pip install -U --exists-action=s -r requirements.txt
```

# Stack trace
```
Running setup.py (path:/tmp/pip-p45yo0-build/setup.py) egg_info for package from file:///vagrant/xxhash-repro/dep
    Traceback (most recent call last):
      File "<string>", line 17, in <module>
      File "/tmp/pip-p45yo0-build/setup.py", line 2, in <module>
        setup(name='dep', setup_requires=['xxhash'])
      File "/usr/lib/python2.7/distutils/core.py", line 111, in setup
        _setup_distribution = dist = klass(attrs)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 262, in __init__
        self.fetch_build_eggs(attrs['setup_requires'])
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 287, in fetch_build_eggs
        replace_conflicting=True,
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 631, in resolve
        dist = best[req.key] = env.best_match(req, ws, installer)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 874, in best_match
        return self.obtain(req, installer)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/pkg_resources.py", line 886, in obtain
        return installer(requirement)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/dist.py", line 338, in fetch_build_egg
        return cmd.easy_install(req)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 636, in easy_install
        return self.install_item(spec, dist.location, tmpdir, deps)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 666, in install_item
        dists = self.install_eggs(spec, download, tmpdir)
      File "/vagrant/xxhash-repro/venv/local/lib/python2.7/site-packages/setuptools/command/easy_install.py", line 842, in install_eggs
        os.path.abspath(dist_filename)
    distutils.errors.DistutilsError: Couldn't find a setup script in /tmp/easy_install-gjY5iT/xxhash-0.5.0.macosx-10.10-x86_64.tar.gz
    Complete output from command python setup.py egg_info:
```

**Comment by ifduyue** [comment]
It seems the problem was caused by a bumb binary xxhash-0.5.0.macosx-10.10-x86_64.tar.gz
I've removed it from PyPI, please try again and see if it's OK

**Comment by tsx** [comment]
It works now, thanks!
